<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Platforms>x64</Platforms>
    <AssemblyName>FrenRaidTools.Engine</AssemblyName>
    <RootNamespace>FrenRaidTools.Engine</RootNamespace>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <ProduceReferenceAssembly>false</ProduceReferenceAssembly>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Assets\plan-*.json" />
    <EmbeddedResource Include="Assets\marks-*.json" />
    <EmbeddedResource Include="..\tools\fights\**\assets\*.json">
      <LogicalName>FrenRaidTools.Engine.Assets.%(Filename)%(Extension)</LogicalName>
    </EmbeddedResource>
    <Compile Include="..\tools\fights\**\*.cs" LinkBase="Local" />
  </ItemGroup>

</Project>
